POST http://localhost:3000/local/editorial-record HTTP/1.1
content-type: application/json

{
    "documentName": "testDocument1",
    "contentSource": "string",
    "informationType": "string",
    "s3Location": "string"
}

###

POST http://localhost:3000/local/editorial-record HTTP/1.1
content-type: application/json

{
    "documentName": "testDocument2",
    "contentSource": "string",
    "informationType": "string",
    "document": {
        "jurisdiction": "string",
        "documentTitle": "string",
        "createdBy": "string",
        "internallyCreated": true,
        "schemaType": "Internal",
        "contentSource": "string",
        "informationType": "string",
        "createdDateTime": "2021-08-18T10:29:51.960+01:00",
        "version": "1.0",
        "feedFormat": "text/plain",
        "taxonomyTerms": [
            {
                "tagId": "sdfsdfsdf",
                "facetType": "Topics",
                "inScheme": [
                    "http://www.dods.co.uk/taxonomy/instance/Topics"
                ],
                "termLabel": "Term 4",
                "ancestorTerms": [
                    {
                        "tagId": "sdfsdfsdf",
                        "termLabel": "Term 2",
                        "rank": 1
                    },
                    {
                        "tagId": "sdfsdfsdf",
                        "termLabel": "Term 1",
                        "rank": 0
                    }
                ],
                "alternative_labels": [
                    "Term B",
                    "Term C"
                ]
            }
        ],
        "documentContent": "html content of the document"
    }
}