#! /usr/bin/env bash

# Reads environment variables from serverless stage to set them up locally

set -eo pipefail

STAGE=${SERVERLESS_STAGE:-dev}
echo '# This file is auto generated by setenv.sh script' > ${STAGE}.env
echo '# do not modify it manually' >> ${STAGE}.env

# run serverless print to get a JSON representation of the runtime config
# extract only the environment definitions
SLS_ENV=$(SLS_DEPRECATION_DISABLE='*' npx serverless print --stage $STAGE --format json | jq '.provider.environment' )

readarray -t ENVS <<<"${SLS_ENV}"

for line in "${ENVS[@]}"; do
   if [[ $line =~ [{}] ]]; then
      continue
   fi

   # Get rid of final comma
   DEF=${line%,}

   # replace ': ' with '='
   DEF=${DEF/: /=}

   # Get rid of all double quotes
   DEF=${DEF//\"/}

   echo export $DEF >> ${STAGE}.env
done
exit 0