service: dods-taxonomy-service

configValidationMode: warn

frameworkVersion: ^2.54.0

variablesResolutionMode: 20210326

projectDir: ../

provider:
  name: aws
  region: eu-west-1
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  deploymentBucket:
    name: pip-${self:provider.stage}-services-lambdas

  lambdaHashingVersion: 20201221
  stackTags:
    service: ${self:service}
    env: ${self:provider.stage}
    version: 1
    teamsEmail: dods.project@somoglobal.com
    team: dods
  tags:
    myTag1: myTag1
  tracing:
    apiGateway: true
    lambda: true
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "xray:PutTraceSegments"
        - "xray:PutTelemetryRecords"
      Resource:
        - "*"
  vpc:
    securityGroupIds: ${file(../env-config.${self:provider.stage}.js):securityGroupIds, file(../vpc.local.js):securityGroupIds}
    subnetIds: ${file(../env-config.${self:provider.stage}.js):subnetIds, file(../vpc.local.js):subnetIds}

  apiGateway:
    restApiId: ${file(../env-config.${self:provider.stage}.js):apiGatewayId, "local"} 
    restApiRootResourceId: ${file(../env-config.${self:provider.stage}.js):apiRootResourceId, "local"} 
    description: Default Gateway for ${self:provider.stage} deployed by Terraform

  environment:
    NODE_ENV: ${opt:NODE_ENV, 'test'}
    SERVERLESS_STAGE: ${self:provider.stage}
    SERVERLESS_PORT: ${self:custom.serverless-offline.httpPort}
    ES_CLOUD_ID: ${env:ES_CLOUD_ID}
    ES_KEY_ID: ${env:ES_KEY_ID}
    ES_API_KEY: ${env:ES_API_KEY}

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules:
      forceInclude:
        - express
    keepOutputDirectory: false
  serverless-offline:
    httpPort: 3000
  prune:
    automatic: true
    number: 1
  dependsOn:
    enabled: true
    chains: 8
  localstack:
    stages:
      # list of stages for which the plugin should be enabled
      - local
    host: http://localhost # optional - LocalStack host to connect to
    edgePort: 4566 # optional - LocalStack edge port to connect to
    autostart: false # optional - Start LocalStack in Docker on Serverless deploy
    # lambda:
    #   # Enable this flag to improve performance
    #   mountCode: True
    docker:
      # Enable this flag to run "docker ..." commands as sudo
      sudo: False
    # Enable or disable caching globally
    apiGatewayCaching:
      enabled: true

plugins:
  - serverless-webpack
  - serverless-prune-plugin
  - serverless-localstack
  - serverless-dependson-plugin
  - serverless-offline
  - serverless-api-gateway-caching

package:
  include:
    - node_modules/**

functions:

  taxonomies:
    handler: src/handlers/taxonomies/index.handle
    description: Triggered when http request comes
    events:
      - http:
          method: get
          path: taxonomies
          caching:
            enabled: false
  taxonomyTree:
    handler: src/handlers/taxonomyTree/index.handle
    description: Return the tree of all taxonomy topics
    timeout: 20
    events:
      - http:
          method: get
          path: taxonomy/tree
          caching:
            enabled: true
  taxonomyTopicsTree:
    handler: src/handlers/taxonomyTopicsTree/index.handle
    description: Triggered when http request comes
    timeout: 20
    events:
      - http:
          method: get
          path: taxonomy/topics/tree
          caching:
            enabled: true
  taxonomyOrganisationsTree:
    handler: src/handlers/taxonomyOrganisationsTree/index.handle
    description: Triggered when http request comes
    timeout: 20
    events:
      - http:
          method: get
          path: taxonomy/organisations/tree
          caching:
            enabled: true