@clientAccountId=cd44bad6-8eeb-4870-abb8-72d297ea7a3e

### search Collections
GET {{host}}/collections?clientAccountId={{clientAccountId}}&startsWith=Coll&sortBy=name&sortDirection=ASC HTTP/1.1

### search Collections V2
GET {{host}}/collections?clientAccountId={{clientAccountId}}&sortBy=name&sortDirection=ASC HTTP/1.1

### search Collections V3
GET {{host}}/collections HTTP/1.1