openapi: 3.0.0
info:
  description: DODS Schedule Service API
  version: 1.0.0
  title: DODS Schedule Service
  contact:
    email: kenanhancer@gmail.com
  license:
    name: GPL 3.0
    url: "https://www.gnu.org/licenses/gpl-3.0.html"
servers:
  - url: /api

paths:
  /scheduler:
    post:
      operationId: createSchedule
      summary: "Create a watcher schedule for doc publishing"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - clientAccount
              properties:
                clientAccount:
                  $ref: '#/components/schemas/createScheduleParameters'
      responses:
        "200":
          $ref: "#/components/responses/CreateSchedule"
        "400":
          $ref: "#/components/responses/BadRequest"
        "404":
          $ref: "#/components/responses/NotFound"

  /scheduler/alert:
    post:
      operationId: createAlertSchedule
      summary: "Create an alert schedule"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - clientAccount
              properties:
                clientAccount:
                  $ref: '#/components/schemas/createAlertScheduleParameters'
      responses:
        "200":
          $ref: "#/components/responses/CreateAlertSchedule"
        "400":
          $ref: "#/components/responses/BadRequest"
        "404":
          $ref: "#/components/responses/NotFound"

  /scheduler/{scheduleId}:
    get:
      operationId: getSchedule
      parameters:
        - in: path
          name: scheduleId
          schema:
            type: string
            format: uuid
          required: true
          description: UUID of the Schedule to get
      responses:
        "200":
          $ref: "#/components/responses/GetSchedule"
        "400":
          $ref: "#/components/responses/BadRequest"
        "404":
          $ref: "#/components/responses/NotFound"
    delete:
      operationId: deleteSchedule
      summary: "Delete schedule for doc publishing"
      parameters:
        - $ref: '#/components/parameters/scheduleId'
      responses:
        "200":
          $ref: "#/components/responses/DeleteSchedule"
        "400":
          $ref: "#/components/responses/BadRequest"
        "404":
          $ref: "#/components/responses/NotFound"
    put:
      operationId: updateSchedule
      summary: "Update schedule for doc publishing"
      parameters:
        - $ref: '#/components/parameters/scheduleId'
      requestBody:
        $ref: "#/components/requestBodies/scheduleUpdateBody"
      responses:
        "200":
          $ref: "#/components/responses/UpdateSchedule"
        "400":
          $ref: "#/components/responses/BadRequest"
        "404":
          $ref: "#/components/responses/NotFound"

  /scheduler/{scheduleId}/activate:
    put:
      operationId: activateSchedule
      summary: "activate schedule"
      parameters:
        - $ref: '#/components/parameters/scheduleId'
      responses:
        "200":
          $ref: "#/components/responses/activateSchedule"
        "400":
          $ref: "#/components/responses/BadRequest"
        "404":
          $ref: "#/components/responses/NotFound"
  /scheduler/{scheduleId}/deactivate:
    put:
      operationId: deactivateSchedule
      summary: "deactivate schedule"
      parameters:
        - $ref: '#/components/parameters/scheduleId'
      responses:
        "200":
          $ref: "#/components/responses/deactivateSchedule"
        "400":
          $ref: "#/components/responses/BadRequest"
        "404":
          $ref: "#/components/responses/NotFound"

components:
  schemas:
    Message:
      type: object
      properties:
        message:
          type: string
    Errors:
      type: object
      properties:
        errors:
          type: object
          additionalProperties:
            type: array
            items:
              type: string
    FullSchedule:
      type: object
      properties:
        scheduleId:
          type: string
          example: 008f811e5ccf44d3a0df5b7f70a8e85d
        scheduleType:
          type: string
          example: publishing
        cron:
          type: string
          example: "0 0 13 24 DEC ? 2021"
    FullAlertSchedule:
      type: object
      properties:
        scheduleId:
          type: string
          example: 008f811e5ccf44d3a0df5b7f70a8e85d
        collectionId:
          type: string
          example: 008f811e5ccf44d3a0df5b7f70a8e85d
        cron:
          type: string
          example: "0 0 13 24 DEC ? 2021"
    UpdateScheduleReturn:
      type: object
      properties:
        scheduleId:
          type: string
          example: 008f811e5ccf44d3a0df5b7f70a8e85d
        cron:
          type: string
          example: "0 0 13 24 DEC ? 2021"

    DeleteScheduleReturn:
      type: object
      properties:
        success:
          type: string
          example: true
        message:
          type: string
          example: schedule with ID 008f811e5ccf44d3a0df5b7f70a8e85d deleted

    activateScheduleReturn:
      type: object
      properties:
        success:
          type: string
          example: true
        message:
          type: string
          example: schedule with ID 008f811e5ccf44d3a0df5b7f70a8e85d activated

    deactivateScheduleReturn:
      type: object
      properties:
        success:
          type: string
          example: true
        message:
          type: string
          example: schedule with ID 008f811e5ccf44d3a0df5b7f70a8e85d deactivated

    createScheduleParameters:
      type: object
      required:
        - scheduleId
        - scheduleType
        - cron
      properties:
        scheduleId:
          type: string
          example: 008f811e5ccf44d3a0df5b7f70a8e85d
        scheduleType:
          type: string
          example: publishing
        cron:
          type: string
          example: "0 0 13 24 DEC ? 2021"

    createAlertScheduleParameters:
      type: object
      required:
        - scheduleId
        - collectionId
        - cron
      properties:
        scheduleId:
          type: string
          example: 008f811e5ccf44d3a0df5b7f70a8e85d
        collectionId:
          type: string
          example: 008f811e5ccf44d3a0df5b7f70a8e85d
        cron:
          type: string
          example: "0 0 13 24 DEC ? 2021"

  parameters:
    scheduleId:
      in: path
      name: scheduleId
      schema:
        type: string
      required: true
      example: d290f1ss-6c54-4b01-98e6-d701748f7151

    deleteSchedule:
      in: query
      name: DeleteSchedule
      schema:
        type: object
        required:
          - scheduleId
        properties:
          scheduleId:
            type: string
            example: 008f811e5ccf44d3a0df5b7f70a8e85d

  responses:
    NotFound:
      description: The specified resource was not found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Message"
    BadRequest:
      description: Bad Request. Input must be valid
      content:
        application/json:
          schema:
            allOf:
              - $ref: "#/components/schemas/Message"
              - $ref: "#/components/schemas/Errors"
    NotAcceptable:
      description: Not Acceptable.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Message"
    GetSchedule:
      description: "Response from scheduler get"
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/FullSchedule'
    CreateSchedule:
      description: "Response from scheduler creation"
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/FullSchedule'

    CreateAlertSchedule:
      description: "Response from scheduler creation"
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/FullAlertSchedule'

    DeleteSchedule:
      description: "Response from scheduler deletion"
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/DeleteScheduleReturn'
    UpdateSchedule:
      description: "Response from scheduler updation"
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UpdateScheduleReturn'
    activateSchedule:
      description: "Response from scheduler activation"
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/activateScheduleReturn'
    deactivateSchedule:
      description: "Response from scheduler deactivation"
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/deactivateScheduleReturn'


  requestBodies:
    scheduleUpdateBody:
      description: "Payload to update a collection"
      content:
        application/json:
          schema:
            type: object
            required:
              - cron
            properties:
              cron:
                type: string
                example: "0 0 13 24 DEC ? 2021"