POST /local/collections HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{
    "clientAccountId": "a170742a-f84d-40e9-9176-8fd6568149f7",
    "name": "Collection Name",
    "createdById": "9b48f3e1-fcc7-4c8a-8bfd-e7d62ce42aee"
}