service: migration-step-2

frameworkVersion: '2'
projectDir: ../
variablesResolutionMode: 20210326
configValidationMode: error
useDotenv: true

plugins:
  - serverless-python-requirements
  - serverless-offline
custom:
  resource_prefix: migration-step-2
  app_acronym: migration-step-2-bucket
  default_stage: dev
  stage: ${opt:stage, self:custom.default_stage}
  stack_name: ${self:custom.app_acronym}-${self:custom.stage}
  region: ${opt:region, self:provider.region}
  deletion_policy: Delete
  s3_input_bucket: pip-${self:provider.stage}-migration-stage-1-output
  s3_output_bucket: pip-${self:provider.stage}-migration-stage-2-output
  s3_key_base: ${opt:s3_key_base, self:custom.stage}
  queue_name: pip-${self:provider.stage}-migration-stage-2-queue.standard
  pythonRequirements:
    pythonBin: python3

package:
  patterns:
    - '!node_modules/**'
    - '!.idea/**'
    - '!env/**'
    - '!README.md'
    - '!package.json'
    - '!package-lock.json'
    - '!.requirements/**'
    - '!requirements.txt'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  region: eu-west-1
  stage: ${opt:stage, 'dev'}
  deploymentBucket:
    name: pip-${self:provider.stage}-scrapping-lambdas

  environment:
    SERVERLESS_STAGE: ${self:provider.stage}
    KEY_PREFIX: ${self:custom.resource_prefix}
    REGION: ${file(../serverless.common.yml):custom.region}
    INPUT_BUCKET: ${self:custom.s3_input_bucket}
    OUTPUT_BUCKET: ${self:custom.s3_output_bucket}
    S3_KEY_BASE: ${self:custom.s3_key_base}
    SQS_QUEUE: ${self:custom.queue_name}
    ES_CLOUD_ID: ${ssm:/infra/elastic/cloud_id}
    ES_KEY_ID: ${ssm:/infra/elastic/key_id}
    ES_API_KEY: ${ssm:/infra/elastic/api_key}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: "arn:aws:s3:::*"

    - Effect: "Allow"
      Action:
        - "sqs:*"
      Resource: arn:aws:sqs:${self:custom.region}:${file(../serverless.common.yml):custom.organizations.${self:provider.stage}}:pip-${self:provider.stage}-migration-stage-2-queue.standard

functions:
  migrate:
    name: migration-step-2-publisher-${sls:stage}
    description: Publish filepath to SQS for migration content from DODS step-1
    handler: handler.run
    timeout: 900
  receiver:
    name: migration-step-2-receiver-${sls:stage}
    description: Receive filepath to SQS for migration content from DODS step-1
    handler: handler.consumer
    timeout: 900
    events:
      - sqs:
          arn: arn:aws:sqs:${self:custom.region}:${file(../serverless.common.yml):custom.organizations.${self:provider.stage}}:pip-${self:provider.stage}-migration-stage-2-queue.standard
          batchSize: 1
