@contentType = application/json

### SignIn

# @name signin
POST {{signIn.host}}/signIn HTTP/1.1
Content-Type: {{contentType}}

{
    "email": "{{signIn.email}}",
    "password": "{{signIn.password}}"
}

### Call sayHell oas Turkish

@accessToken = {{signin.response.body.accessToken}}

# @name sayHello
GET {{host}}/sayHello HTTP/1.1
authorization: bearer {{accessToken}}
Content-Type: {{contentType}}
language: Turkish
title: Mr
firstName: Kenan
lastName: Hancer

### Call sayHello as English

@accessToken = {{signin.response.body.accessToken}}

# @name sayHello
GET {{host}}/sayHello HTTP/1.1
authorization: bearer {{accessToken}}
Content-Type: {{contentType}}
language: English
title: Mr
firstName: Kenan
lastName: Hancer