### get Collections by alert V1


PUT {{host}}/collections/86cc34ae-47db-407c-b18d-bccfbd600e11/alerts/fb9d9220-c01f-4e4a-b15c-ee4a33846fb7/schedule HTTP/1.1

{
  "isScheduled": true,
  "hasKeywordHighlight": false,
  "timezone": "-5",
  "schedule": "DATE",
  "updatedBy": "6340c08f-0a01-41c1-8434-421f1fff3d1e",
  "alertTemplateId": 1
}