# The manifest for the "frontend-dods-pip" service.
# Read the full specification for the "Load Balanced Web Service" type at:
#  https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/

# Your service name will be used in naming your resources like log groups, ECS services, etc.
name: frontend-dods-pip
type: Load Balanced Web Service

# Distribute traffic to your service.
http:
  # Requests to this path will be forwarded to your service.
  # To match all requests you can use the "/" path.
  path: '/'
  # You can specify a custom health check path. The default is "/".
  # healthcheck: '/'

# Configuration for your containers and service.
image:
  location: 390773179818.dkr.ecr.eu-west-1.amazonaws.com/dods-pip/frontend-dods-pip:d796fd76640da9d3b5590eda73e9566eaec6fGio
  # Port exposed through your container to route traffic to it.
  port: 3000

cpu: 256       # Number of CPU units for the task.
memory: 512    # Amount of memory in MiB used by the task.
count: 1       # Number of tasks that should be running in your service.
exec: true     # Enable running commands in your container.

variables:
  SECRET_COOKIE_PASSWORD: 2gyZ3GDw3LHZQKDhPmPDL3sjREVRXPr8
  BACKEND_API_KEY: 8b8pv1rGpssR8eeUMjQPjsi8dC2ztrP1GTG1K2w
  APP_API_URL: https://emhumq7ktf.execute-api.eu-west-1.amazonaws.com/dev  
  NODE_ENV: dev

#secrets:                      # Pass secrets from AWS Systems Manager (SSM) Parameter Store.
#  GITHUB_TOKEN: GITHUB_TOKEN  # The key is the name of the environment variable, the value is the name of the SSM parameter.

# You can override any of the values defined above by environment.
#environments:
#  test:
#    count: 2               # Number of tasks to run for the "test" environment.
