service: elasticsearch-manager

frameworkVersion: '2'
projectDir: ../
variablesResolutionMode: 20210326
configValidationMode: error
useDotenv: true

plugins:
  - serverless-python-requirements
  - serverless-offline
custom:
  resource_prefix: elasticsearch-manager
  app_acronym: dods-elasticsearch-manager
  default_stage: dev
  stage: ${opt:stage, self:custom.default_stage}
  stack_name: ${self:custom.app_acronym}-${self:custom.stage}
  region: ${opt:region, self:provider.region}
  pythonRequirements:
    pythonBin: python3

package:
  patterns:
    - '!node_modules/**'
    - '!.idea/**'
    - '!env/**'
    - '!README.md'
    - '!package.json'
    - '!package-lock.json'
    - '!.requirements/**'
    - '!requirements.txt'

provider:
  name: aws
  runtime: python3.7
  lambdaHashingVersion: 20201221
  region: eu-west-1
  stage: ${opt:stage, 'dev'}
  deploymentBucket:
    name: pip-${self:provider.stage}-services-lambdas

  environment:
    ALERT_Q_URL: https://sqs.${aws:region}.amazonaws.com/${aws:accountId}/${self:provider.stage}-instant-alert-queue.fifo
    ES_CLOUD_ID: ${ssm:/infra/elastic/cloud_id}
    ES_KEY_ID: ${ssm:/infra/elastic/key_id}
    ES_API_KEY: ${ssm:/infra/elastic/api_key}
    JWK_URL: 'https://cognito-idp.${self:provider.region}.amazonaws.com/${cf:dods-iam-${self:provider.stage}.UserPoolId}/.well-known/jwks.json'
    KEY_PREFIX: ${self:custom.resource_prefix}
    REGION: eu-west-1
    SERVERLESS_STAGE: ${self:provider.stage}

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "sqs:SendMessage"
      Resource: arn:aws:sqs:${aws:region}:${aws:accountId}:${self:provider.stage}-instant-alert-queue.fifo


functions:
  elastic-run:
    name: elasticsearch-manager-${self:provider.stage}
    description: Elasticsearch index manager
    handler: handler.run
    timeout: 90
  contentIndexer:
    name: content-indexer-${self:provider.stage}
    description: Elasticsearch content indexer
    handler: content_indexer.run
    timeout: 900
