@contentType = application/json

### SignIn

# @name signin
POST {{signIn.host}} HTTP/1.1
Content-Type: {{contentType}}

{
    "email": "{{signIn.email}}",
    "password": "{{signIn.password}}"
}

### Call sayEnglishHello

@accessToken = {{signin.response.body.accessToken}}

# @name sayEnglishHello
GET {{host}}/sayEnglishHello HTTP/1.1
authorization: bearer {{accessToken}}
Content-Type: {{contentType}}
title: Mr
firstName: Kenan
lastName: Hancer