### Set Alert Recipients
@collectionId = cd44bad6-8eeb-4870-abb8-72d297ea7a14
@alertId = c2211873-3076-4a9a-b951-409258b933d9
PUT {{host}}/collections/{{collectionId}}/alerts/{{alertId}}/recipients HTTP/1.1
Content-Type: application/json

{
  "updatedBy": "6c16a036-2439-4b78-bf29-8069f4cd6c0b",
  "recipients": [{
    "userId": "6340c08f-0a01-41c1-8434-421f1fff3d1e"
  }]
}