openapi: 3.0.0
info:
  description: DODS Boilerplate
  version: 1.0.0
  title: DODS Boilerplate
  contact:
    email: kenanhancer@gmail.com
  license:
    name: GPL 3.0
    url: "https://www.gnu.org/licenses/gpl-3.0.html"
servers:
  - url: /api

paths:
  /health:
    get:
      operationId: health
      summary: "Get Health Message"
      description: "Get Health Message"
      responses:
        "200":
        "404":
          $ref: "#/components/responses/NotFound"

  /sayHello:
    get:
      operationId: sayHello
      summary: "Get Greeting Message"
      description: "Get Greeting Message"
      parameters:
        - $ref: "#/components/parameters/language"
        - $ref: "#/components/parameters/title"
        - $ref: "#/components/parameters/firstName"
        - $ref: "#/components/parameters/lastName"
      responses:
        "200":
          $ref: "#/components/responses/SayHello"
        "400":
          $ref: "#/components/responses/BadRequest"
        "404":
          $ref: "#/components/responses/NotFound"

components:
  schemas:
    Message:
      type: object
      properties:
        message:
          type: string
    Errors:
      type: object
      properties:
        errors:
          type: object
          additionalProperties:
            type: array
            items:
              type: string

  parameters:
    language:
      in: header
      name: language
      schema:
        type: string
        enum:
          - English
          - Turkish
      required: true
      description: Language of Greeting Message
    title:
      in: header
      name: title
      schema:
        type: string
        enum:
          - Mr
          - Mrs
          - Miss
          - Ms
      required: true
      description: Title of Person
    firstName:
      in: header
      name: firstName
      schema:
        type: string
      required: true
      description: First name of Person
    lastName:
      in: header
      name: lastName
      schema:
        type: string
      required: true
      description: Last name of Person

  responses:
    NotFound:
      description: The specified resource was not found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Message"
    BadRequest:
      description: Bad Request. Input must be valid
      content:
        application/json:
          schema:
            allOf:
              - $ref: "#/components/schemas/Message"
              - $ref: "#/components/schemas/Errors"
    NotAcceptable:
      description: Not Acceptable.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Message"
    SayHello:
      description: "{greeting} {title} {firstName} {lastName}"
      content:
        application/json:
          schema:
            type: "string"
          examples:
            Kenan:
              value: Merhaba Mr Kenan Hancer
            Larissa:
              value: Hello Mrs Larissa Cottrell
